version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes
      POSTGRES_PASSWORD: "4ELkOgBE6U-mqsC5OXQbtMxNF2v8kpxo"
    volumes:
      - notes_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "7VQIoqHybDphTVT5DedBTDXJt8whoM_o"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  notes_data:
